version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: swe-microservice-nginx
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8808:80"
    depends_on:
      - carservice
      - db

  db:
    image: mysql:8.0
    container_name: swe-microservice-db
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "4306:3306"
    env_file:
      - ./environments/dev/.env

  carservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swe-microservice-carservice
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    env_file:
      - ./environments/dev/.env
    depends_on:
      - db
